# Comand to run when starting the bot.
# Argv style also supported: ["python", "simplebot.py"]
command = "cargo run"

# Directory in which to run the command.
# It is recommended to use an absolute path here.
working_directory = "/Users/steam/git/RipleyPlanetWarsBot"
